std = "lua51"
unused_args = false
unused_secondaries = false
allow_defined_top = true
max_line_length = false
ignore = {
   "611",
   "612",
   "614",
}
exclude_files = {
   "Libs/**",
}

files["**/*.lua"] = {
   globals = {
      "MedaUI",
      _G = {other_fields = true},
      SlashCmdList = {read_only = false, other_fields = true},
      StaticPopupDialogs = {read_only = false, other_fields = true},
      ColorPickerFrame = {read_only = false, other_fields = true},
      C_Timer = {
         other_fields = true,
         fields = {
            After = {read_only = false},
            NewTimer = {read_only = false},
            NewTicker = {read_only = false},
         },
      },
   },

   read_globals = {
      "_G",
      "ADDON_LOADED",
      "AddonCompartmentFrame",
      "BackdropTemplate",
      "BasicScriptErrors",
      "BugGrabber",
      "C_AddOns",
      "C_ChallengeMode",
      "C_ChatInfo",
      "C_PvP",
      "C_RestrictedActions",
      "C_Secrets",
      "C_Spell",
      "C_Timer",
      "C_UnitAuras",
      "CopyTable",
      "CreateFrame",
      "CreateColor",
      "CreateFont",
      "EnumerateFrames",
      "GameFontNormal",
      "GameFontNormalLarge",
      "GameFontNormalSmall",
      "GameFontHighlightSmall",
      "GameTooltip",
      "GetMinimapShape",
      "GetPhysicalScreenSize",
      "GetAddOnMemoryUsage",
      "GetBuildInfo",
      "GetCursorPosition",
      "GetFramerate",
      "GetInstanceInfo",
      "GetNetStats",
      "GetNumGroupMembers",
      "GetScreenHeight",
      "GetScreenWidth",
      "GetTime",
      "InCombatLockdown",
      "IsShiftKeyDown",
      "IsInGroup",
      "IsInInstance",
      "IsInRaid",
      "LibStub",
      "Minimap",
      "Mixin",
      "PlaySoundFile",
      "ReloadUI",
      "ResetCursor",
      "ScriptErrorsFrame",
      "SetCursor",
      "SlashCmdList",
      "StaticPopupDialogs",
      "StaticPopup_Hide",
      "StaticPopup_Show",
      "UIParent",
      "UISpecialFrames",
      "UpdateAddOnMemoryUsage",
      "WorldFrame",
      "WOW_PROJECT_ID",
      "WOW_PROJECT_MAINLINE",
      "canaccessvalue",
      "canaccesstable",
      "collectgarbage",
      "date",
      "debugstack",
      "format",
      "geterrorhandler",
      "hasanysecretvalues",
      "issecretvalue",
      "issecrettable",
      "loadstring",
      "print",
      "securecallfunction",
      "seterrorhandler",
      "strmatch",
      "strupper",
      "time",
      "tinsert",
      "tremove",
      "wipe",
   },
}
